# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-24.04

variables:
  - name: WebAppKind
    value: webAppLinux

  - name: ConnectedServiceName
    value: ac59adbd-9024-4f57-8cb4-2c0d37ea8cc2

  - name: WebAppName
    value: azure-omorales-cd-pipeline

    
stages: 

 # STAGE 1: Build and Package
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildJob
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '**/*.war'
            TargetFolder: '$(build.artifactstagingdirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'warfile'
            publishLocation: 'Container'

 # STAGE 2: Deploy to Development
  - stage: DeployQA
    displayName: 'Deploy to QA'
    dependsOn: Build
    condition: succeeded()

    jobs:
    
      - deployment: DeploymentJob
        environment: 'QA'
        strategy:
          runOnce:
            deploy:             
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Current Build Artifacts'
                  inputs:
                   buildType: 'current'                   
                   artifactName: 'warfile' # Name of your published artifact
                   downloadPath: '$(System.ArtifactsDirectory)' # Destination folder

                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy Azure App Service'
                  
                  inputs:
                    azureSubscription: '$(ConnectedServiceName)'
                    appType: '$(WebAppKind)'
                    WebAppName: '$(WebAppName)'
                    packageForLinux: '$(build.artifactstagingdirectory)/**/*.war'
                    StartupCommand: '$(Parameters.StartupCommand)'                  

 # STAGE 3: Automation Testing artifact
  - stage: RegressionTesting
    displayName: 'Regression Testing'
    dependsOn: DeployQA
    condition: succeeded()
    
    jobs:    
      - job: Regression
        
        steps:
        - task: Maven@4
          displayName: 'Maven $(System.DefaultWorkingDirectory)/_Automation_MX/pom.xml'
          inputs:
            azureSubscription: 'ac59adbd-9024-4f57-8cb4-2c0d37ea8cc2'
            mavenPomFile: '$(System.DefaultWorkingDirectory)/_Automation_MX/pom.xml'
            goals: test